GET http://localhost:5000/api/search/presets/deals
###
GET http://localhost:5000/api/search
###
GET http://localhost:5000/api/search/filters
###
GET http://localhost:5000/api/search?q=apple
###
GET http://localhost:5000/api/search?category=fruits
###
GET http://localhost:5000/api/search?minPrice=5&maxPrice=20